name: Pruebas Automatizadas Go

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Descargar el codigo
        uses: actions/checkout@v3

      - name: Configurar entorno Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Inicializar modulo y descargar SQLite
        working-directory: ./server
        run: |
          go get modernc.org/sqlite
          go mod tidy

      - name: Ejecutar Pruebas Unitarias
        working-directory: ./server
        run: go test -v ./...